### PR TITLE
Main content

### PR DESCRIPTION
**Pull request by lekegitrepo**
Hi, 
 We are looking forward to your help and professional advice on how to make any  necessary improvement on this project. Thanks.
Best wishes.

Thais & Temitayo.

### CODE REVIEW

**Comment by Oghenebrume50** [comment]
Reviewing.........

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi guys good work on this one it looks really nice but we need to make some few fixes 

For the top section
 on large screens
 - It contains TWN logo at the top left corner of the row.
- TWN logo disappears.

## Categories (Apps, GERA, Tech, etc) section
### Medium screens
* [x] It aligns 2 category boxes per row.

# Small screens
* [x] It aligns 1 category box per row.

**Comment by Oghenebrume50** [comment]
- [OPTIONAL ] Use article tags for all the articles as opposed to using regular divs
-  [REQUIRED] make stickler work for this project.

Please fix these things and submit for re-review, kudos for a good start  :smiley:

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
Hi team a good job :+1: , the webpage looks awesome now, but it seems the wrong stickler configuration is used, why was stylint removed, please? I am sure that is the one referenced in the pathright, please read the project instructions again on pathright and use the correct stickler configuration, then fix errors too. Do this and submit for re-review.

**Comment by lekegitrepo** [comment]
Hi, we have corrected all the errors, but there are four errors that the stickler is complaining about. 
We checked, but is not an error because the indentation is right and other stuff that it marked as an error were actually not an error. Can you please check and give us feedback?
Thanks for your help and guidance.
Thais & Temitayo.

**Review by stratospherique — CHANGES_REQUESTED** [review]
Try to use linters on your local environment. Use this [guide](https://github.com/microverseinc/linters-config/tree/master/css), it's easier to fix these errors on your local environment.

After you follow the steps in the guide, open the stylesheet file and browse to problems in the terminal. That should give you a list of your errors. :wink: :wink:

**Review by Oghenebrume50 — APPROVED** [review]
Looks good guys, that was some battle with stickler :smiley:, this is approved :+1:

**Comment by thsvr** [comment]
@Oghenebrume50 actually it was a war but we won haha. 

Thanks for your help.

Cheers,

Temitayo and Thaís

**Pull request merged**
